<?php

return [
    'val_town_url' => env('VAL_TOWN_URL', 'https://fit.val.run/'),
    'admin_password' => env('ADMIN_PASSWORD', ''),
    'total_weeks' => 7,
    'days' => ['mon', 'tue', 'thu', 'fri'],
    'sets_per_slot' => 3,
    'default_overload_increment' => 2.0,
    'default_overload_frequency' => 'weekly',

    'splits' => [
        'mon' => [
            'title' => 'Maandag: Upper A (Kracht Focus)',
            'slots' => ['slot_a1', 'slot_a2', 'slot_a3', 'slot_a4', 'slot_a5', 'slot_a6'],
        ],
        'tue' => [
            'title' => 'Dinsdag: Upper B (Volume & Schouders)',
            'slots' => ['slot_b1', 'slot_b2', 'slot_b3', 'slot_b4', 'slot_b5', 'slot_b6'],
        ],
        'thu' => [
            'title' => 'Donderdag: Upper A (Kracht & Borst)',
            'slots' => ['slot_a1', 'slot_a2', 'slot_a3', 'slot_a4', 'slot_a5', 'slot_a6'],
        ],
        'fri' => [
            'title' => 'Vrijdag: Upper B (Hypertrofie & Armen)',
            'slots' => ['slot_b1', 'slot_b2', 'slot_b3', 'slot_b4', 'slot_b5', 'slot_b6'],
        ],
    ],

    'catalog' => [
        'slot_a1' => [
            'defaultName' => 'Barbell Bench Press',
            'targetReps' => 8,
            'restType' => 'Compound Borst',
            'restTime' => 150,
            'muscles' => 'Grote Borstspier, Triceps, Voorste Schouder',
            'equipment' => 'Barbell + Drukbank',
            'tips' => [
                'Trek je schouderbladen stevig samen en plant ze in de bank.',
                'Ellebooghoek circa 45° tot 70° ten opzichte van je romp houden.',
                'Zet je voeten plat in de vloer voor stevige leg drive stabiliteit.',
            ],
            'alternatives' => [
                'Barbell Bench Press', 'Incline Barbell Press', 'Dumbbell Bench Press', 'Incline Dumbbell Press',
                'Opdrukken (Klassieke Push-ups)', 'Decline Push-ups (Voeten op Bankje)', 'Deficit Push-ups',
                'Diamond Push-ups', 'Opdrukken (Breed / Wide Grip)', 'Decline Barbell Press', 'Decline Dumbbell Press',
                'Dumbbell Floor Press', 'Close-Grip Barbell Bench Press', 'Pauze Barbell Bench Press (2s Stop)',
                'Tempo Dumbbell Bench Press',
            ],
        ],
        'slot_a2' => [
            'defaultName' => 'Barbell Row',
            'targetReps' => 8,
            'restType' => 'Compound Rug',
            'restTime' => 120,
            'muscles' => 'Latissimus Dorsi, Bovenrug, Biceps',
            'equipment' => 'Barbell',
            'tips' => [
                'Scharnier diep in de heup met een neutrale, rechte wervelkolom.',
                'Trek de stang richting je navel en stuur de beweging vanuit je ellebogen.',
                'Houd bovenin 1 seconde vast met krachtig samengetrokken schouderbladen.',
            ],
            'alternatives' => [
                'Barbell Row', 'Pendlay Row (Dead Stop)', 'Underhand Barbell Row (Yates Row)', 'Barbell Row (Wijde Grip)',
                'Dumbbell One-Arm Row', 'Chest-Supported Dumbbell Row', 'Dumbbell Gorilla Row', 'Meadows Row (Landmine)',
                'T-Bar Row (Barbell in Hoek)', 'Inverted Barbell Row', 'Seal Row (Op Bankje)',
            ],
        ],
        'slot_a3' => [
            'defaultName' => 'Incline Dumbbell Press',
            'targetReps' => 10,
            'restType' => 'Accessoire Borst',
            'restTime' => 90,
            'muscles' => 'Bovenkant Borst (Claviculair), Triceps, Voorste Schouder',
            'equipment' => 'Dumbbells + Verstelbaar Bankje (30°-45°)',
            'tips' => [
                'Zet de bankhoek op 30° tot 45° om schouderbelasting optimaal te beperken.',
                'Gecontroleerd en diep zakken voor maximale stretch op de bovenborst.',
                'Druk omhoog in een vloeiende lichte boog zonder de gewichten te ketsen.',
            ],
            'alternatives' => [
                'Incline Dumbbell Press', 'Dumbbell Chest Flyes', 'Incline Dumbbell Flyes', 'Floor Dumbbell Flyes',
                'Incline Dumbbell Hex Press', 'Dumbbell Floor Press', 'Opdrukken (Klassieke Push-ups)',
                'Decline Push-ups (Voeten op Bankje)', 'Deficit Push-ups', 'Diamond Push-ups', 'Decline Dumbbell Press',
                'Svend Press (Schijven)', 'Push-ups met Voeten op Bankje',
            ],
        ],
        'slot_a4' => [
            'defaultName' => 'Barbell Shrugs',
            'targetReps' => 12,
            'restType' => 'Isolatie Traps',
            'restTime' => 75,
            'muscles' => 'Trapezius (Nek & Bovenrug)',
            'equipment' => 'Barbell of Zware Dumbbells',
            'tips' => [
                'Schouders zuiver recht omhoog tillen naar de oren (nooit cirkelen).',
                'Bovenin 1-2 tellen hard aanspannen (peak contraction).',
                'Langzaam laten zakken tot een volledige rek op de nekspieren.',
            ],
            'alternatives' => [
                'Barbell Shrugs', 'Dumbbell Shrugs', 'Behind-The-Back Barbell Shrugs', 'Incline Bench Dumbbell Shrugs',
                'Dumbbell Shrugs met Pauze (2s Squeeze)', 'Barbell Upright Row', 'Dumbbell Upright Row',
                "Farmer's Walk (Heavy Carry)",
            ],
        ],
        'slot_a5' => [
            'defaultName' => 'Dumbbell Lateral Raises',
            'targetReps' => 12,
            'restType' => 'Isolatie Schouders',
            'restTime' => 60,
            'muscles' => 'Zijkant Schouders (Mediale Delts)',
            'equipment' => 'Lichte Dumbbells',
            'tips' => [
                'Leun minimaal voorover en leid de opwaartse heffing met de ellebogen.',
                'Houd een kleine vaste buiging in de ellebooggewrichten.',
                'Niet meewippen met je romp; isoleer zuiver de zijkant van de schouder.',
            ],
            'alternatives' => [
                'Dumbbell Lateral Raises', 'Seated Dumbbell Lateral Raises', 'Leaning Dumbbell Lateral Raises',
                'Lying Incline Lateral Raises', 'Prone Incline Lateral Raises', 'Barbell Upright Row',
                'Dumbbell Front Raises', 'Around The World Raises',
            ],
        ],
        'slot_a6' => [
            'defaultName' => 'Dumbbell Bicep Curls',
            'targetReps' => 10,
            'restType' => 'Isolatie Armen',
            'restTime' => 75,
            'muscles' => 'Biceps Brachii & Brachialis',
            'equipment' => 'Dumbbells',
            'tips' => [
                'Houd de ellebogen gefixeerd langs de zijkant van je ribbenkast.',
                'Draai de handpalmen tijdens het omhoog curlen naar buiten (supinatie).',
                'Laat in 2-3 tellen strikt en gecontroleerd excentrisch zakken.',
            ],
            'alternatives' => [
                'Dumbbell Bicep Curls', 'Barbell Bicep Curls', 'Hammer Curls (Dumbbells)', 'Incline Dumbbell Curls',
                'Preacher Curls (Dumbbell/EZ)', 'Concentration Curls', 'Reverse Grip Barbell Curls',
                'Spider Curls (Borst op Bank)', '21s Bicep Curls',
            ],
        ],
        'slot_b1' => [
            'defaultName' => 'Dumbbell Pullover',
            'targetReps' => 10,
            'restType' => 'Compound Rug / Lats',
            'restTime' => 90,
            'muscles' => 'Latissimus Dorsi, Bovenrug, Serratus',
            'equipment' => 'Dumbbell + Vlak Bankje',
            'tips' => [
                'Lig stabiel met je bovenrug op het fitnessbankje met voeten plat op de vloer.',
                'Houd de dumbbell met beide handen in een ruitgreep vast boven je borst.',
                'Laat het gewicht met licht gebogen ellebogen in een gecontroleerde boog achter je hoofd zakken.',
            ],
            'alternatives' => [
                'Dumbbell Pullover', 'Pull-ups (Optrekken Bovengreep)', 'Chin-ups (Optrekken Ondergreep)',
                'Barbell Pullover (Liggend op Bankje)', 'Chest-Supported Dumbbell Row', 'Underhand Barbell Row (Yates Row)',
                'Meadows Row (Landmine)', 'Inverted Barbell Row', 'T-Bar Row (Barbell in Hoek)', 'Seal Row (Op Bankje)',
            ],
        ],
        'slot_b2' => [
            'defaultName' => 'Seated Dumbbell Shoulder Press',
            'targetReps' => 8,
            'restType' => 'Compound Schouders',
            'restTime' => 120,
            'muscles' => 'Voorste & Zijkant Schouders, Triceps',
            'equipment' => 'Dumbbells + Rechtop Bankje (75°-80°)',
            'tips' => [
                'Zet de rugleuning op ca. 75°-80° (iets achterover spaart het schoudergewricht).',
                'Druk verticaal omhoog zonder overmatige holling in je onderrug.',
                'Zakken tot minimaal oorhoogte voor een volledige, veilige spierrek.',
            ],
            'alternatives' => [
                'Seated Dumbbell Shoulder Press', 'Barbell Overhead Press (OHP)', 'Seated Barbell Press', 'Arnold Press',
                'Standing Dumbbell Shoulder Press', 'Landmine Shoulder Press', 'Push Press (Barbell)',
                'Dumbbell High Incline Press',
            ],
        ],
        'slot_b3' => [
            'defaultName' => 'Dumbbell Floor Press',
            'targetReps' => 10,
            'restType' => 'Accessoire Borst/Triceps',
            'restTime' => 90,
            'muscles' => 'Borst, Triceps (Lockout & Druksterkte)',
            'equipment' => 'Dumbbells + Vloermat',
            'tips' => [
                'Ga plat op de grond liggen met de knieën gebogen en voeten plat.',
                'Laat de bovenarmen zachtjes op de vloer rusten (1 seconde dead-stop).',
                'Explosief uitdrukken voor maximale triceps- en borstcontractie.',
            ],
            'alternatives' => [
                'Dumbbell Floor Press', 'Opdrukken (Klassieke Push-ups)', 'Decline Push-ups (Voeten op Bankje)',
                'Close-Grip Barbell Bench Press', 'Push-ups (Standard)', 'Diamond Push-ups', 'Decline Dumbbell Press',
                'Floor Dumbbell Flyes', 'JM Press (Dumbbells of Barbell)', 'Deficit Push-ups',
            ],
        ],
        'slot_b4' => [
            'defaultName' => 'Dumbbell One-Arm Row',
            'targetReps' => 10,
            'restType' => 'Accessoire Rug',
            'restTime' => 90,
            'muscles' => 'Latissimus Dorsi, Rhomboids, Bovenrug',
            'equipment' => 'Dumbbell + Vlak Bankje',
            'tips' => [
                'Plaats knie en steunhand op de bank met een neutrale, kaarsrechte rug.',
                'Trek de dumbbell in een lichte boog naar je heup/achterzak.',
                'Onderin de lat en schouderblad volledig laten uitstrekken.',
            ],
            'alternatives' => [
                'Dumbbell One-Arm Row', 'Chest-Supported Dumbbell Row', 'Barbell Row', 'Renegade Rows (Dumbbell)',
                'Seal Row (Op Hoog Bankje)', 'Kroc Rows (Heavy Reps)', 'Meadows Row (Landmine)', 'Incline Dumbbell Row',
            ],
        ],
        'slot_b5' => [
            'defaultName' => 'Rear Delt Flyes',
            'targetReps' => 12,
            'restType' => 'Isolatie Achterkant Schouders',
            'restTime' => 60,
            'muscles' => 'Achterste Schouderkop (Posterior Delts)',
            'equipment' => 'Lichte Dumbbells',
            'tips' => [
                'Diep voorovergebogen staan of met je borst op een schuin bankje steunen.',
                'Armen zijwaarts heffen met een lichte, vaste elleboogknik.',
                'Focus puur op de achterkant van de schouders, trek niet met de nek.',
            ],
            'alternatives' => [
                'Rear Delt Flyes', 'Dumbbell Face Pulls (Liggend op Schuin Bankje)', 'Barbell Rear Delt Raise',
                'Seated Rear Delt Flyes', 'Bench-Supported Y-Raises', 'Prone Incline Rear Delt Raises',
            ],
        ],
        'slot_b6' => [
            'defaultName' => 'Bench Dips',
            'targetReps' => 12,
            'restType' => 'Isolatie Triceps',
            'restTime' => 75,
            'muscles' => 'Triceps Brachii',
            'equipment' => 'Fitnessbankje (Lichaamsgewicht)',
            'tips' => [
                'Blijf met je rug vlak langs de rand van het bankje op en neer bewegen.',
                'Zakken tot maximaal een hoek van 90 graden in de ellebogen.',
                'Druk krachtig en geconcentreerd uit vanuit de achterkant van je bovenarm.',
            ],
            'alternatives' => [
                'Bench Dips', 'Dumbbell Overhead Tricep Extension', 'Barbell Lying Tricep Extension (Skull Crushers)',
                'Dumbbell Skull Crushers (Liggend op Bankje)', 'Incline Dumbbell Overhead Extension',
                'Dumbbell Kickbacks', 'Close-Grip Push-ups', 'Tate Press (Dumbbells)',
            ],
        ],
    ],
];
