#!/usr/bin/env bash
DEPLOY_APP=mark
DEPLOY_DEFAULT_URL=''
DEPLOY_DB_CONNECTIONS=mysql
DEPLOY_TABLE_PREFIX=''
DEPLOY_EXCLUDE_PREFIX=foodtracker_
DEPLOY_EXPECTED_DATABASE=''
DEPLOY_CATALOG_MIGRATIONS=false
DEPLOY_SESSION_CHECK=false
DEPLOY_TEST_CONNECTION=sqlite
DEPLOY_PERSISTENT_ENV_FILES=()
